services:
  - type: web
    name: streamkji
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: PAYDUNYA_MASTER_KEY
        sync: false
      - key: PAYDUNYA_PRIVATE_KEY
        sync: false
      - key: PAYDUNYA_TOKEN
        sync: false
      - key: PAYDUNYA_MODE
        sync: false